const contractAddress = "0xdaFcBE1Fc87C51f9E3376042608Aa7C59CE89fbf"; // Replace with your own contract address
const chain = 'polygon'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Shroomies NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'What are Shroomies? Shroomies is an NFT project created to bring the everyone in the community together with a Shroomie!';
const h1_presale_coming_soon = "Shroomie NFT Drop Coming Soon!";
const h1_presale_mint = "Pre-Sale Minting Open📢🍄";
const h1_public_mint = "Get your Shroomies🍄🙌";
const h2_presale_coming_soon = "Be one of the first's to get a Shroomie only a few spots";
const h2_presale_mint = "Congrats you are one of the firsts to get a Shroomie";
const p_presale_coming_soon = "We are launching Pre-sale on July the 4th 4:00 UTC. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not on the pre-sale list for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the pre-sale list for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your pre-sale mint. Thank you! 🎉";
const p_public_mint = "Public minting is now open get your Shroomie🍄";
const button_presale_coming_soon = "Get on the pre-sale list";
const button_presale_mint_whitelisted = "Mint Your Shroomie";
const button_presale_mint_not_whitelisted = "Get on the pre-sale list";
const button_presale_already_minted = "Join The Shroomie Community if you haven't already!";
const button_public_mint = "Mint Your Shroomie";
const mint_failed = "Minting failed. 😢 Please try again.";